apiVersion: v1
kind: Secret
metadata:
  name: cloudcart-secrets
  namespace: ecommerce
type: Opaque
stringData:
  MYSQL_ROOT_PASSWORD: "root123"
  JWT_SECRET: "change-this-jwt-secret-in-real-production"
